pipeline {
    agent any
    stages {
        stage('Check Changes and Run in Parallel') {
            steps {
                script {
                    // Get the list of changed files
                    def changedFiles = sh(script: 'git diff --name-only HEAD~1', returnStdout: true).trim()

                    echo "Changed files: ${changedFiles}"
                    
                    // Define the subdirectories and their respective pipeline jobs
                    def subdirectories = ['frontend', 'backend']
                    // Load docker script
                    def dockerBuild = load "src/Jenkins-templates/docker.groovy"

                    def registry = "058264560763.dkr.ecr.us-east-1.amazonaws.com/nt-devops"

                    echo "dockerBuild object: ${dockerBuild}"

                    subdirectories.each { subdir ->
                        if (changedFiles.contains("src/$subdir/")) {
                            dockerBuild.buildDockerImage("src/$subdir", "$registry/$subdir", "latest")
                            sh "docker push $registry/$subdir:latest"
                        }
                    }
                }
            }
        }
    }
}
